# -*- coding: utf-8 -*-
"""Trabalho python Helena e Victor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9WDbqKAz5YaMwepJqaC4MYsauentedP
"""

estudantes = {
    "202614269": [6.9, 8.4, 7.0, 8.2, 7.5, 8.0],
    "202614187": [4.5, 8.7, 4.0, 9.0, 5.0, 10.0],
    "199714083": [8.2] #media informada
}


print("--- Medias por matriculas ---")
for matricula, notas in estudantes.items():
    media = sum(notas) / len(notas)
    print(f"Matrícula: {matricula} | Média: {media:.2f}")

estudantes = {
    "202614269": [6.9, 8.4, 7.0, 8.2, 7.5, 8.0],
    "202614187": [4.5, 8.7, 4.0, 9.0, 5.0, 10.0],
    "199714083": [8.2]
}

# 1. Cria lista de médias (CR) já ordenada
ranking = sorted([(m, sum(n)/len(n)) for m, n in estudantes.items()], key=lambda x: x[1], reverse=True)

print("--- TOP 3 RANKING ---")
for m, cr in ranking[:3]:
    print(f"Matrícula {m}: CR {cr:.2f}")

# 2. Informa por escrito a maior nota
print(f"\nA MAIOR NOTA (MAIOR CR) É DA MATRÍCULA: {ranking[0][0]}")

estudantes = {
    "202614269": [6.9, 8.4, 7.0, 8.2, 7.5, 8.0],
    "202614187": [4.5, 8.7, 4.0, 9.0, 5.0, 10.0],
    "199714083": [8.2]
}

# Calcula médias e ordena
ranking = sorted([(m, sum(n)/len(n)) for m, n in estudantes.items()], key=lambda x: x[1], reverse=True)
posicoes = ["1°", "2°", "3°"]

print("--- RANKING DE CR ---")
for i in range(3):
    print(f"{posicoes[i]}: CR {ranking[i][1]:.2f}")

# Resultado final detalhado
m_vencedora, cr_vencedor = ranking[0]
print(f"\nA MAIOR NOTA (MAIOR CR) É DA MATRÍCULA {m_vencedora}, FICANDO EM {posicoes[0].upper()} LUGAR COM CR {cr_vencedor:.2f}")